name: Run Robot Tests with ChromeDriver

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install robotframework robotframework-seleniumlibrary webdriver-manager

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | sed 's/[^0-9]*//g')
        wget https://chromedriver.storage.googleapis.com/$(CHROME_VERSION)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Run Robot Tests
      run: |
        robot primeiro_teste.robot
